name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: gradragregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push images to ACR
        run: |
          docker compose -f prod.yaml build
          docker compose -f prod.yaml push
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az container create \
            --name crawler-container\
            --resource-group gradragGroup \
            --environment gradragenv \
            --image gradragregistry.azurecr.io/gradrag-crawler:latest \
            --target-port 8000 \
            --ingress external

