name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t gradragregistry.azurecr.io/gradrag-crawler:latest .
          docker push gradragregistry.azurecr.io/gradrag-crawler:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp create \
            --name gradragcrawlerapp\
            --resource-group gradragGroup \
            --environment gradragenv \
            --image gradragregistry.azurecr.io/gradrag-crawler:latest \
            --target-port 8080 \
            --ingress external

